baseURL = "https://we-gold.github.io"
languageCode = "en-us"
title = "Weaver Goldman"
theme = "digital-garden"
copyright = "Weaver Goldman ©"


[params]
  name = "Weaver Goldman"
  description = "Programmer, Learning Enthusiast, and Biology Novice"
  initials = "WG"
  # googleAnalytics = ""

  [[params.social]]
    name = "Github"
    link = "https://github.com/We-Gold"
    icon = "fab fa-github"

  [[params.social]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/weaver-goldman/"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Digital Garden"
    url = "/garden/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
#   [[menu.main]]
#     name = "Library"
#     url = "/library/"
#     weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'